spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sm
    password: yena
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update #create, update 중 개발에 따라 선택
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  logging.level:
    org.hibernate.SQL: debug
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


